### ISSUE TITLE
[Error Middleware] log an info message even for 4xx errors

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-handlers#47]
When a handler returns an error, we add the error message as a field to the logger:

https://github.com/Scalingo/go-handlers/blob/ee88df962afc42ffb717b67fb95e9bf8d7adb519/error_middleware.go#L45-L48

(btw we should use `log.WithError` rather than `log.WithField`)

But in the `writeError` function, we never log any message if the status code is 400:

https://github.com/Scalingo/go-handlers/blob/ee88df962afc42ffb717b67fb95e9bf8d7adb519/error_middleware.go#L59-L72

I would be in favor of writing a log *error* message for 5xx errors, and *info* message in all other cases. What do you think?

**Comment by Soulou** [comment]
I'm in favor.
